apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fabric-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: fabric-operator
    spec:
      containers:
      - name: fabric-operator
        image: grapebaba/fabric-operator:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
